with rows(competition_code, season, round, home_county, away_county, sport_code, ground_name, match_date, throw_in_time, home_score, away_score, status, winner) as (
  values
    ('nfl', 2022, 'Division 1 Final', 'Kerry', 'Mayo', 'gaelic_football', 'Croke Park', '2022-04-03'::date, null::time, '3-19', '0-13', 'completed', 'home'),
    ('nfl', 2023, 'Division 1 Final', 'Mayo', 'Galway', 'gaelic_football', 'Croke Park', '2023-04-02'::date, null::time, '0-14', '0-11', 'completed', 'home'),
    ('nfl', 2024, 'Division 1 Final', 'Derry', 'Dublin', 'gaelic_football', 'Croke Park', '2024-03-31'::date, null::time, null, null, 'completed', 'home'),
    ('nfl', 2025, 'Division 1 Final', 'Kerry', 'Mayo', 'gaelic_football', 'Croke Park', null::date, null::time, null, null, 'completed', 'home'),
    ('nhl', 2022, 'Division 1 Final', 'Waterford', 'Cork', 'hurling', 'Semple Stadium', '2022-04-02'::date, null::time, '4-20', '1-23', 'completed', 'home'),
    ('nhl', 2023, 'Division 1 Final', 'Limerick', 'Kilkenny', 'hurling', 'Croke Park', null::date, null::time, '2-20', '0-15', 'completed', 'home'),
    ('nhl', 2024, 'Division 1 Final', 'Clare', 'Kilkenny', 'hurling', 'Semple Stadium', '2024-04-06'::date, '19:15'::time, '3-16', '1-20', 'completed', 'home'),
    ('nhl', 2025, 'Division 1 Final', 'Cork', 'Tipperary', 'hurling', 'Croke Park', null::date, null::time, '3-24', '0-23', 'completed', 'home'),
    ('tailteann_cup', 2022, 'Final', 'Westmeath', 'Cavan', 'gaelic_football', 'Croke Park', '2022-07-09'::date, null::time, '2-14', '1-13', 'completed', 'home'),
    ('tailteann_cup', 2023, 'Final', 'Meath', 'Down', 'gaelic_football', 'Croke Park', '2023-07-15'::date, null::time, '2-13', '0-14', 'completed', 'home'),
    ('tailteann_cup', 2024, 'Final', 'Down', 'Laois', 'gaelic_football', 'Croke Park', '2024-07-13'::date, null::time, '0-14', '2-6', 'completed', 'home'),
    ('tailteann_cup', 2025, 'Final', 'Kildare', 'Limerick', 'gaelic_football', 'Croke Park', '2025-07-12'::date, null::time, '1-24', '2-19', 'completed', 'home'),
    ('joe_mcdonagh_cup', 2021, 'Final', 'Westmeath', 'Kerry', 'hurling', null, null::date, null::time, '2-28', '1-24', 'completed', 'home'),
    ('joe_mcdonagh_cup', 2022, 'Final', 'Antrim', 'Kerry', 'hurling', null, null::date, null::time, null, null, 'completed', 'home'),
    ('joe_mcdonagh_cup', 2023, 'Final', 'Carlow', 'Offaly', 'hurling', 'Croke Park', '2023-05-27'::date, null::time, '2-29', '1-31', 'completed', 'home'),
    ('joe_mcdonagh_cup', 2024, 'Final', 'Offaly', 'Laois', 'hurling', null, null::date, null::time, '2-23', '0-26', 'completed', 'home'),
    ('joe_mcdonagh_cup', 2025, 'Final', 'Kildare', 'Laois', 'hurling', 'Croke Park', '2025-06-08'::date, '13:45'::time, '2-26', '1-19', 'completed', 'home'),
    ('christy_ring_cup', 2022, 'Final', 'Kildare', 'Mayo', 'hurling', null, null::date, null::time, null, null, 'completed', 'home'),
    ('christy_ring_cup', 2023, 'Final', 'Meath', 'Derry', 'hurling', null, null::date, null::time, null, null, 'completed', 'home'),
    ('christy_ring_cup', 2024, 'Final', 'Kildare', 'Derry', 'hurling', null, null::date, null::time, '4-21', '1-22', 'completed', 'home'),
    ('nickey_rackard_cup', 2021, 'Final', 'Mayo', 'Tyrone', 'hurling', null, null::date, null::time, '2-27', '1-14', 'completed', 'home'),
    ('nickey_rackard_cup', 2022, 'Final', 'Tyrone', 'Roscommon', 'hurling', null, null::date, null::time, null, null, 'completed', 'home'),
    ('nickey_rackard_cup', 2023, 'Final', 'Wicklow', 'Donegal', 'hurling', null, null::date, null::time, null, null, 'completed', 'home'),
    ('nickey_rackard_cup', 2024, 'Final', 'Donegal', 'Mayo', 'hurling', null, null::date, null::time, '3-17', '0-22', 'completed', 'home'),
    ('nickey_rackard_cup', 2025, 'Final', 'Roscommon', 'Mayo', 'hurling', null, null::date, null::time, '3-16', '1-24', 'completed', 'home'),
    ('lory_meagher_cup', 2021, 'Final', 'Fermanagh', 'Cavan', 'hurling', null, null::date, null::time, null, null, 'completed', 'home'),
    ('lory_meagher_cup', 2022, 'Final', 'Louth', 'Longford', 'hurling', null, null::date, null::time, null, null, 'completed', 'home'),
    ('leinster_sfc', 2021, 'Final', 'Dublin', 'Kildare', 'gaelic_football', 'Croke Park', '2021-08-01'::date, null::time, null, null, 'completed', 'home'),
    ('leinster_sfc', 2022, 'Final', 'Dublin', 'Kildare', 'gaelic_football', 'Croke Park', '2022-05-28'::date, null::time, null, null, 'completed', 'home'),
    ('leinster_sfc', 2023, 'Final', 'Dublin', 'Louth', 'gaelic_football', 'Croke Park', '2023-05-14'::date, null::time, null, null, 'completed', 'home'),
    ('leinster_sfc', 2024, 'Final', 'Dublin', 'Louth', 'gaelic_football', 'Croke Park', '2024-05-12'::date, null::time, '1-19', '2-12', 'completed', 'home'),
    ('leinster_sfc', 2025, 'Final', 'Louth', 'Meath', 'gaelic_football', 'Croke Park', '2025-05-11'::date, '16:00'::time, '3-14', '1-18', 'completed', 'home'),
    ('munster_sfc', 2021, 'Final', 'Kerry', 'Cork', 'gaelic_football', 'Fitzgerald Stadium', '2021-07-25'::date, null::time, '4-22', '1-9', 'completed', 'home'),
    ('munster_sfc', 2022, 'Final', 'Kerry', 'Limerick', 'gaelic_football', 'Fitzgerald Stadium', '2022-05-28'::date, null::time, '1-28', '0-8', 'completed', 'home'),
    ('munster_sfc', 2023, 'Final', 'Kerry', 'Clare', 'gaelic_football', 'TUS Gaelic Grounds', '2023-05-07'::date, null::time, '5-14', '0-15', 'completed', 'home'),
    ('munster_sfc', 2024, 'Final', 'Kerry', 'Clare', 'gaelic_football', 'Cusack Park (Ennis)', '2024-05-05'::date, null::time, '0-23', '1-13', 'completed', 'home'),
    ('munster_sfc', 2025, 'Final', 'Kerry', 'Clare', 'gaelic_football', null, '2025-05-04'::date, null::time, '4-20', '0-21', 'completed', 'home'),
    ('ulster_sfc', 2021, 'Final', 'Tyrone', 'Monaghan', 'gaelic_football', null, null::date, null::time, null, null, 'completed', 'home'),
    ('ulster_sfc', 2022, 'Final', 'Derry', 'Donegal', 'gaelic_football', null, null::date, null::time, null, null, 'completed', 'home'),
    ('ulster_sfc', 2023, 'Final', 'Derry', 'Armagh', 'gaelic_football', null, '2023-05-14'::date, null::time, null, null, 'completed', 'home'),
    ('ulster_sfc', 2024, 'Final', 'Donegal', 'Armagh', 'gaelic_football', 'St Tiernach''s Park', '2024-05-12'::date, null::time, null, null, 'completed', 'home'),
    ('ulster_sfc', 2025, 'Final', 'Donegal', 'Armagh', 'gaelic_football', 'St Tiernach''s Park', '2025-05-10'::date, '17:25'::time, '2-23', '0-28', 'completed', 'home'),
    ('connacht_sfc', 2021, 'Final', 'Mayo', 'Galway', 'gaelic_football', 'Croke Park', '2021-07-25'::date, null::time, null, null, 'completed', 'home'),
    ('connacht_sfc', 2022, 'Final', 'Galway', 'Roscommon', 'gaelic_football', 'Pearse Stadium', '2022-05-29'::date, '13:45'::time, null, null, 'completed', 'home'),
    ('connacht_sfc', 2023, 'Final', 'Galway', 'Sligo', 'gaelic_football', 'MacHale Park', '2023-05-07'::date, null::time, null, null, 'completed', 'home'),
    ('connacht_sfc', 2024, 'Final', 'Galway', 'Mayo', 'gaelic_football', 'Pearse Stadium', '2024-05-05'::date, null::time, null, null, 'completed', 'home'),
    ('connacht_sfc', 2025, 'Final', 'Galway', 'Mayo', 'gaelic_football', 'MacHale Park', '2025-05-04'::date, '16:00'::time, null, null, 'completed', 'home'),
    ('leinster_shc', 2021, 'Final', 'Kilkenny', 'Dublin', 'hurling', 'Croke Park', null::date, null::time, null, null, 'completed', 'home'),
    ('leinster_shc', 2022, 'Final', 'Kilkenny', 'Galway', 'hurling', 'Croke Park', '2022-06-04'::date, null::time, null, null, 'completed', 'home'),
    ('leinster_shc', 2023, 'Final', 'Kilkenny', 'Galway', 'hurling', 'Croke Park', '2023-06-11'::date, null::time, '4-21', '2-26', 'completed', 'home'),
    ('leinster_shc', 2024, 'Final', 'Kilkenny', 'Dublin', 'hurling', 'Croke Park', '2024-06-08'::date, null::time, null, null, 'completed', 'home'),
    ('leinster_shc', 2025, 'Final', 'Kilkenny', 'Galway', 'hurling', 'Croke Park', '2025-06-08'::date, '16:00'::time, null, null, 'completed', 'home'),
    ('munster_shc', 2021, 'Final', 'Limerick', 'Tipperary', 'hurling', 'Páirc Uí Chaoimh', '2021-07-18'::date, null::time, '2-29', '3-21', 'completed', 'home'),
    ('munster_shc', 2022, 'Final', 'Limerick', 'Clare', 'hurling', 'Semple Stadium', '2022-06-05'::date, null::time, '1-29', '0-29', 'completed', 'home'),
    ('munster_shc', 2023, 'Final', 'Limerick', 'Clare', 'hurling', 'TUS Gaelic Grounds', '2023-06-11'::date, null::time, '1-23', '1-22', 'completed', 'home'),
    ('munster_shc', 2024, 'Final', 'Limerick', 'Clare', 'hurling', 'Semple Stadium', '2024-06-09'::date, null::time, '1-26', '1-20', 'completed', 'home'),
    ('munster_shc', 2025, 'Final', 'Cork', 'Limerick', 'hurling', 'TUS Gaelic Grounds', null::date, null::time, '2-27', '1-30', 'completed', 'home'),
    ('ai_shc', 2026, 'Final', 'Limerick', 'Galway', 'hurling', 'Croke Park', '2026-07-19'::date, null::time, '1-29', '1-18', 'completed', 'home'),
    ('ai_sfc', 2026, 'Semi-Final', 'Kerry', 'Dublin', 'gaelic_football', 'Croke Park', '2026-07-12'::date, null::time, '2-18', '0-20', 'completed', 'home'),
    ('ai_sfc', 2026, 'Semi-Final', 'Mayo', 'Louth', 'gaelic_football', 'Croke Park', '2026-07-11'::date, null::time, '3-23', '0-15', 'completed', 'home'),
    ('ai_sfc', 2026, 'Final', 'Kerry', 'Mayo', 'gaelic_football', 'Croke Park', '2026-07-26'::date, '15:30'::time, null, null, 'scheduled', null)
)
insert into public.matches (
  match_type, competition, competition_id, season, round, home_county_team_id, away_county_team_id,
  ground_id, match_date, throw_in_time, played_at, province, status, home_score, away_score, winner
)
select
  'county',
  comp.name,
  comp.id,
  r.season,
  r.round,
  hct.id,
  act.id,
  g.id,
  r.match_date,
  r.throw_in_time,
  case when r.match_date is not null then (r.match_date + coalesce(r.throw_in_time, '15:00'::time)) at time zone 'Europe/Dublin' else null end,
  comp.province,
  r.status,
  r.home_score,
  r.away_score,
  r.winner
from rows r
join public.competitions comp on comp.code = r.competition_code
join public.counties hc on hc.name = r.home_county
join public.county_teams hct on hct.county_id = hc.id and hct.sport_code = r.sport_code::public.sport_code
join public.counties ac on ac.name = r.away_county
join public.county_teams act on act.county_id = ac.id and act.sport_code = r.sport_code::public.sport_code
left join public.grounds g on g.name = r.ground_name;
